
from agents import drafting_agent, seo_optimization_agent, editing_refinement_agent, chief_agent
from crewai import Task

drafting_task = Task(
    description=(
        "Generate a draft on {topic} for a LinkedIn post. "
        "Focus on creating content that is informative, engaging, and aligned with current trends or developments in {topic}."
    ),
    expected_output=(
        "A compelling draft LinkedIn post on {topic}, capturing the essence of {topic} and resonating with the target audience on LinkedIn."
    ),
    agent=drafting_agent,
)

editing_task = Task(
    description=(
        "Refine and polish a draft LinkedIn post on {topic}. "
        "Focus on improving grammar, clarity, and overall readability while ensuring alignment with brand voice and objectives. "
        "Add relevant emojis in a professional way."
    ),
    expected_output=(
        "A polished LinkedIn post on {topic}, enhanced in grammar, clarity, and readability. "
        "The post effectively communicates the intended message while maintaining consistency with brand guidelines."
    ),
    agent=editing_refinement_agent,
)

seo_task = Task(
    description=(
        "Optimize a LinkedIn post on {topic} for searchability and discoverability. "
        "Identify and integrate relevant keywords and hashtags to improve visibility on LinkedIn’s platform."
    ),
    expected_output=(
        "An optimized LinkedIn post on {topic}, improved with relevant keywords and hashtags. "
        "The post is structured to enhance search engine visibility and attract the target audience effectively."
    ),
    agent=seo_optimization_agent,
)

# visual_task = Task(
#     description=(
#         "Create or suggest visual elements for a LinkedIn post on {topic}. "
#         "Generate images, infographics, or videos that enhance the post's message and appeal to your LinkedIn connections."
#     ),
#     expected_output=(
#         "Visual elements (images, infographics, or videos) for a LinkedIn post on {topic}, "
#         "designed to complement and enhance the post's content. "
#         "Ensure the visuals are engaging and relevant to the topic, suitable for sharing on your LinkedIn profile."
#     ),
#     tools=[], 
#     agent=visual_content_agent,

# )

chief_task = Task(
    description=(
        "Aggregate and compile the final results from various tasks into a cohesive LinkedIn post. "
        "Integrate content generated by drafting, refinement, SEO optimization, and visual content tasks into a unified presentation."
    ),
    expected_output=(
        "A finalized LinkedIn post on {topic}, incorporating outputs from drafting, refinement, SEO optimization, and visual content tasks. "
        "The post is engaging, informative, and tailored to resonate with the target audience on LinkedIn."
    ),
    agent=chief_agent,
    async_execution=False,
    output_file="task3.md",
)
