from crewai import Task
from agents import instagram_content_compiler,instagram_content_formatter,instagram_drafting_agent,instagram_image_creator,instagram_refinement_agent,instagram_seo_agent

drafting_task_instagram = Task(
    description=(
        "Generate a draft for an Instagram post on {topic}. "
        "Focus on creating content that is visually appealing, engaging, and aligns with current trends or developments in {topic}."
    ),
    expected_output=(
        "A compelling draft Instagram post on {topic}, capturing the essence of {topic} and resonating with Instagram users."
    ),
    agent=instagram_drafting_agent,  
)

editing_task_instagram = Task(
    description=(
        "Refine and polish a draft Instagram post on {topic}. "
        "Focus on enhancing grammar, clarity, and overall readability while ensuring alignment with the intended style and engagement goals. "
        "Incorporate relevant emojis tastefully."
    ),
    expected_output=(
        "A polished Instagram post on {topic}, improved in grammar, clarity, and readability. "
        "The post effectively communicates the intended message while maintaining a style that resonates with Instagram users."
    ),
    agent=instagram_refinement_agent,  
)

seo_task_instagram = Task(
    description=(
        "Optimize an Instagram post on {topic} for discoverability and engagement. "
        "Identify and integrate relevant keywords and hashtags to improve visibility on Instagram's platform."
    ),
    expected_output=(
        "An optimized Instagram post on {topic}, enhanced with relevant keywords and hashtags. "
        "The post is structured to maximize discoverability and engagement, appealing to the target audience effectively."
        "Only the top 5 keywords and hashtags must be chosen"
    ),
    agent=instagram_seo_agent,  
)

chief_task_instagram = Task(
    description=(
        "Aggregate and compile the final results from various tasks into a cohesive Instagram post. "
        "Integrate content generated by drafting, refinement, SEO optimization, and image generation into a unified presentation."
    ),
    expected_output=(
        "A finalized Instagram post on {topic}, incorporating outputs from drafting, refinement, SEO optimization, and image generation. "
        "The post is engaging, visually appealing, and tailored to resonate with the target audience on Instagram. "
        "End the post with an interactive call-to-action inviting viewers to engage with the content."
    ),
    agent=instagram_content_compiler,  
)

image_generate_task_instagram = Task(
    description=(
        "Create 3 visually compelling images that capture and enhance the essence of an Instagram post about {topic}. "
        "Each image should be relevant to the content of the post, reflecting the tone and aesthetic of Instagram. "
        "Focus on creating images that add visual appeal and effectively convey the message to engage the Instagram audience."
        "Imagine what the photo you wanna take describe it in a paragraph."
			"Here are some examples for you to follow:"
			"- high tech airplaine in a beautiful blue sky in a beautiful sunset super cripsy beautiful 4k, professional wide shot"
			"- the last supper, with Jesus and his disciples, breaking bread, close shot, soft lighting, 4k, crisp"
			"- an bearded old man in the snows, using very warm clothing, with mountains full of snow behind him, soft lighting, 4k, crisp, close up to the camera"

			"Think creatively and focus on how the image can capture the audience's attention."
    ),
    agent=instagram_image_creator,  
    expected_output=(
        "Three options of photographs that visually represent and complement the Instagram post on {topic}. "
        "Each image should be professional, engaging, and aligned with Instagram's aesthetic and tone. "
        "Include a paragraph describing each photograph, detailing how it captures the essence of the post and engages the Instagram audience."
    ),
)

format_content_task_instagram = Task(
    description='Format the Instagram content in markdown, including image content at the end of the Instagram post.',
    agent=instagram_content_formatter,  
    expected_output='The entire post content around 25 words in the beginning and choose one description among the descriptions generated attach it to the end of the post content format in down to  markdown language',
    context=[chief_task_instagram, image_generate_task_instagram],  
    async_execution=False,
    output_file="outputs/insta_post.md"  
)